pipeline{
    agent{
        label "CI"
    }

 environment {
     APP_VERSION = "1.0"
 }

    stages{
        stage("Stage 1"){
            steps{
                sh 'env'
            }
        }
    }
}