pipeline{
    agent{
        label "CI"
    }

 environment {
     APP_VERSION = "1.0"
     SSH = Credentials('SSH-CENTOS1')
    }

    stages{
        stage("Stage 1"){
            environment {
                APP_VERSION = "2.0"
            }
            steps{
                sh 'env'
            }
        }
    }
}